// Mocks generated by Mockito 5.2.0 from annotations
// in dennis_lechon_crm/test/widget%20tests/customer_feature_test.dart.
// Do not manually edit this file.

import 'dart:ui' as _i2;

import 'package:dennis_lechon_crm/models/customer.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeColor_0 extends _i1.Fake implements _i2.Color {}

/// A class which mocks [Customer].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomer extends _i1.Mock implements _i3.Customer {
  MockCustomer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get firstName =>
      (super.noSuchMethod(Invocation.getter(#firstName), returnValue: '')
          as String);
  @override
  String get middleName =>
      (super.noSuchMethod(Invocation.getter(#middleName), returnValue: '')
          as String);
  @override
  String get lastName =>
      (super.noSuchMethod(Invocation.getter(#lastName), returnValue: '')
          as String);
  @override
  String get celNum =>
      (super.noSuchMethod(Invocation.getter(#celNum), returnValue: '')
          as String);
  @override
  String get telNum =>
      (super.noSuchMethod(Invocation.getter(#telNum), returnValue: '')
          as String);
  @override
  String get adrStreet =>
      (super.noSuchMethod(Invocation.getter(#adrStreet), returnValue: '')
          as String);
  @override
  String get adrBarangay =>
      (super.noSuchMethod(Invocation.getter(#adrBarangay), returnValue: '')
          as String);
  @override
  String get adrCity =>
      (super.noSuchMethod(Invocation.getter(#adrCity), returnValue: '')
          as String);
  @override
  String get adrZipcode =>
      (super.noSuchMethod(Invocation.getter(#adrZipcode), returnValue: '')
          as String);
  @override
  String get adrProvince =>
      (super.noSuchMethod(Invocation.getter(#adrProvince), returnValue: '')
          as String);
  @override
  String get note =>
      (super.noSuchMethod(Invocation.getter(#note), returnValue: '') as String);
  @override
  String get tagName =>
      (super.noSuchMethod(Invocation.getter(#tagName), returnValue: '')
          as String);
  @override
  int get tagIndex =>
      (super.noSuchMethod(Invocation.getter(#tagIndex), returnValue: 0) as int);
  @override
  _i2.Color get tagColor => (super.noSuchMethod(Invocation.getter(#tagColor),
      returnValue: _FakeColor_0()) as _i2.Color);
}
